version: 2

project_name: okt

before:
  hooks:
    - go mod tidy

builds:
  - id: okt
    main: ./cmd/okt
    binary: okt
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: okt
    ids: [okt]
    name_template: 'okt_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  disable: true

release:
  mode: append
  draft: false
  prerelease: auto
