package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSaveBundlePreservesHeaderComments pins the scoped fix from task
// #222: a wiring file that ships with a top-of-file banner comment
// block must keep that block intact across a SaveBundle round-trip.
// Inline / mid-file comments are not yet preserved (full-fidelity
// preservation requires migrating to the yaml.Node API); the saver
// godoc documents the scope.
func TestSaveBundlePreservesHeaderComments(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "omakiten.yaml")
	header := strings.Join([]string{
		"# omakiten wiring — generated by `okt init`.",
		"# Each top-level key has a dedicated reference doc under .docs/.",
		"# Mid-file comments are not preserved by SaveBundle yet (see task #222).",
		"",
	}, "\n") + "\n"

	bundle := Bundle{
		Version: 1,
		Workflows: []Workflow{{
			ID:      1,
			Key:     "demo",
			Name:    "Demo",
			Buckets: []Bucket{{ID: 1, Key: "backlog", Name: "Backlog", Position: 1}},
		}},
		Config: Settings{Workflow: WorkflowSettings{Active: "demo"}},
	}
	if err := SaveBundle(path, bundle); err != nil {
		t.Fatalf("SaveBundle initial: %v", err)
	}
	current, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after first save: %v", err)
	}
	// Prepend the header to simulate a user who hand-added a banner.
	withHeader := []byte(header + string(current))
	if err := os.WriteFile(path, withHeader, 0o644); err != nil {
		t.Fatalf("seed with header: %v", err)
	}

	// Round-trip: re-save the same bundle. The header must survive.
	if err := SaveBundle(path, bundle); err != nil {
		t.Fatalf("SaveBundle round-trip: %v", err)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read after round-trip: %v", err)
	}
	if !strings.HasPrefix(string(got), header) {
		t.Fatalf("header comments lost on round-trip; got prefix %q", firstNRunes(string(got), len(header)+40))
	}
	// Sanity: the actual wiring keys still serialise after the header.
	if !strings.Contains(string(got), "workflows:") {
		t.Fatalf("post-round-trip output missing workflows: %s", got)
	}
}

// TestReadHeaderCommentsHandlesMissingFile asserts a fresh-seed path
// (no existing file at `path`) returns nil rather than erroring, so
// the SaveBundle preservation hook stays no-op friendly.
func TestReadHeaderCommentsHandlesMissingFile(t *testing.T) {
	dir := t.TempDir()
	if got := readHeaderComments(filepath.Join(dir, "missing.yaml")); got != nil {
		t.Fatalf("missing file returned non-nil header: %q", got)
	}
}

// TestReadHeaderCommentsStopsAtFirstContentLine pins the boundary
// rule: only the leading comment + blank-line block is captured;
// content after it (and any later comments) is excluded.
func TestReadHeaderCommentsStopsAtFirstContentLine(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "with-header.yaml")
	body := "# leading note\n\nversion: 1\n# mid-file note\nkit: x\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}
	got := string(readHeaderComments(path))
	if got != "# leading note\n\n" {
		t.Fatalf("readHeaderComments = %q, want only the leading block", got)
	}
}

func firstNRunes(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
