// okt-docs-refresh regenerates auto-derivable documentation from the canonical
// sources under defaults/. Run via `mise run docs:refresh`. See .docs/AUTHORING.md.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "<!-- GENERATED by `mise run docs:refresh` — do not edit by hand. Re-run the task to refresh. -->\n"

var officialPresets = []string{"omakase", "izakaya", "kaiseki", "shokunin"}

type entity struct {
	Slug        string
	Name        string   `yaml:"name"`
	Description string   `yaml:"description"`
	Severity    string   `yaml:"severity,omitempty"`
	Entity      string   `yaml:"entity,omitempty"`
	Default     string   `yaml:"default,omitempty"`
	Laws        []string `yaml:"laws,omitempty"`
	Skills      []string `yaml:"skills,omitempty"`
}

type presetPersona struct {
	Slug   string   `yaml:"slug"`
	Skills []string `yaml:"skills,omitempty"`
}

type presetMCPBinding struct {
	Persona      string   `yaml:"persona,omitempty"`
	Laws         []string `yaml:"laws,omitempty"`
	LawsDisabled []string `yaml:"laws_disabled,omitempty"`
	Templates    []string `yaml:"templates,omitempty"`
	Skills       []string `yaml:"skills,omitempty"`
}

type guard struct {
	Type    string   `yaml:"type"`
	Tag     string   `yaml:"tag,omitempty"`
	Count   int      `yaml:"count,omitempty"`
	Buckets []string `yaml:"buckets,omitempty"`
	Hint    string   `yaml:"hint,omitempty"`
}

type bucket struct {
	ID   int    `yaml:"id"`
	Key  string `yaml:"key"`
	Name string `yaml:"name,omitempty"`
}

type transition struct {
	From   int     `yaml:"from"`
	To     int     `yaml:"to"`
	Guards []guard `yaml:"guards,omitempty"`
}

type workflow struct {
	Key         string                `yaml:"key"`
	Name        string                `yaml:"name,omitempty"`
	Operations  map[string]operations `yaml:"operations,omitempty"`
	Buckets     []bucket              `yaml:"buckets,omitempty"`
	Transitions []transition          `yaml:"transitions,omitempty"`
}

type operations struct {
	Guards []guard `yaml:"guards,omitempty"`
}

type preset struct {
	Key         string                      `yaml:"-"`
	Name        string                      `yaml:"-"`
	Personas    []presetPersona             `yaml:"personas,omitempty"`
	MCPCommands map[string]presetMCPBinding `yaml:"mcp_commands,omitempty"`
	Workflows   []workflow                  `yaml:"workflows,omitempty"`
}

type presetFile struct {
	Kit struct {
		Key  string `yaml:"key"`
		Name string `yaml:"name"`
	} `yaml:"kit"`
	Personas    []presetPersona             `yaml:"personas,omitempty"`
	MCPCommands map[string]presetMCPBinding `yaml:"mcp_commands,omitempty"`
	Workflows   []workflow                  `yaml:"workflows,omitempty"`
}

func main() {
	root := flag.String("root", ".", "project root containing defaults/ and .docs/")
	check := flag.Bool("check", false, "exit non-zero if regenerated output differs from on-disk")
	flag.Parse()

	abs, err := filepath.Abs(*root)
	if err != nil {
		fail("resolve root: %v", err)
	}
	if err := run(abs, *check); err != nil {
		fail("%v", err)
	}
}

func run(root string, check bool) error {
	entities, err := loadAllEntities(root)
	if err != nil {
		return err
	}
	presets, err := loadAllPresets(root)
	if err != nil {
		return err
	}

	generated := map[string]string{}

	generated[".docs/_generated/entities-laws.md"] = renderLaws(entities["laws"])
	generated[".docs/_generated/entities-skills.md"] = renderSimpleEntities(entities["skills"], "skills")
	generated[".docs/_generated/entities-personas.md"] = renderPersonas(entities["personas"])
	generated[".docs/_generated/entities-templates.md"] = renderTemplates(entities["templates"])

	for _, p := range presets {
		generated[fmt.Sprintf(".docs/_generated/presets-%s.md", p.Key)] = renderPreset(p, entities)
	}

	generated[".docs/_generated/tag-vocabulary.md"] = renderTagVocabulary(presets)

	// prompt-costs.md is hand-maintained from `mise run mcp:prompts` output
	// until a dedicated cost-snapshot subtask lands. Reading on disk so
	// includes still resolve, but no overwrite here.

	diffs := []string{}
	for rel, content := range generated {
		full := filepath.Join(root, rel)
		if check {
			existing, err := os.ReadFile(full)
			if err != nil || string(existing) != content {
				diffs = append(diffs, rel)
			}
			continue
		}
		if err := writeFile(full, content); err != nil {
			return fmt.Errorf("write %s: %w", rel, err)
		}
	}

	// Marker-replacement engine: rewrite in-place blocks across .docs/**/*.md.
	docsDir := filepath.Join(root, ".docs")
	if err := processMarkers(docsDir, generated, check, &diffs); err != nil {
		return err
	}

	if check && len(diffs) > 0 {
		sort.Strings(diffs)
		return fmt.Errorf("docs drift detected in:\n  - %s\nrun `mise run docs:refresh` and commit the result. See .docs/AUTHORING.md", strings.Join(diffs, "\n  - "))
	}
	return nil
}

// ---- loaders ----

func loadAllEntities(root string) (map[string]map[string]entity, error) {
	out := map[string]map[string]entity{}
	for _, kind := range []string{"laws", "skills", "personas", "templates"} {
		dir := filepath.Join(root, "defaults", kind)
		es, err := loadEntities(dir)
		if err != nil {
			return nil, fmt.Errorf("load %s: %w", kind, err)
		}
		out[kind] = es
	}
	return out, nil
}

func loadEntities(dir string) (map[string]entity, error) {
	out := map[string]entity{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fm, body, err := splitFrontmatter(raw)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		var e entity
		if err := yaml.Unmarshal(fm, &e); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		e.Slug = strings.TrimSuffix(filepath.Base(path), ".md")
		if e.Description == "" {
			e.Description = firstParagraph(string(body))
		}
		out[e.Slug] = e
		return nil
	})
	return out, err
}

func loadAllPresets(root string) ([]preset, error) {
	out := []preset{}
	for _, key := range officialPresets {
		path := filepath.Join(root, "defaults", "config", key+".yaml")
		raw, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		var pf presetFile
		if err := yaml.Unmarshal(raw, &pf); err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		out = append(out, preset{
			Key:         key,
			Name:        pf.Kit.Name,
			Personas:    pf.Personas,
			MCPCommands: pf.MCPCommands,
			Workflows:   pf.Workflows,
		})
	}
	return out, nil
}

// ---- frontmatter parsing ----

var frontmatterRe = regexp.MustCompile(`(?s)\A---\n(.*?\n)---\n`)

func splitFrontmatter(raw []byte) ([]byte, []byte, error) {
	m := frontmatterRe.FindSubmatchIndex(raw)
	if m == nil {
		return nil, raw, fmt.Errorf("no frontmatter")
	}
	return raw[m[2]:m[3]], raw[m[1]:], nil
}

// ---- renderers ----

func renderLaws(es map[string]entity) string {
	keys := sortedKeys(es)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n# Laws Catalog\n\n")
	b.WriteString("Auto-derived from `defaults/laws/*.md` frontmatter.\n\n")
	b.WriteString("| Slug | Severity | Description |\n|---|---|---|\n")
	for _, k := range keys {
		e := es[k]
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", e.Slug, defaulted(e.Severity, "—"), oneLine(e.Description)))
	}
	return b.String()
}

func renderSimpleEntities(es map[string]entity, kind string) string {
	keys := sortedKeys(es)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("\n# %s Catalog\n\n", titleize(kind)))
	b.WriteString(fmt.Sprintf("Auto-derived from `defaults/%s/*.md` frontmatter.\n\n", kind))
	b.WriteString("| Slug | Description |\n|---|---|\n")
	for _, k := range keys {
		e := es[k]
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", e.Slug, oneLine(e.Description)))
	}
	return b.String()
}

func renderPersonas(es map[string]entity) string {
	keys := sortedKeys(es)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n# Personas Catalog\n\n")
	b.WriteString("Auto-derived from `defaults/personas/*.md` frontmatter.\n\n")
	b.WriteString("| Slug | Description | Skills |\n|---|---|---|\n")
	for _, k := range keys {
		e := es[k]
		skills := "—"
		if len(e.Skills) > 0 {
			skills = "`" + strings.Join(e.Skills, "`, `") + "`"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", e.Slug, oneLine(e.Description), skills))
	}
	return b.String()
}

func renderTemplates(es map[string]entity) string {
	keys := sortedKeys(es)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n# Templates Catalog\n\n")
	b.WriteString("Auto-derived from `defaults/templates/*.md` frontmatter.\n\n")
	b.WriteString("| Slug | Entity | Default | Description |\n|---|---|---|---|\n")
	for _, k := range keys {
		e := es[k]
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", e.Slug, defaulted(e.Entity, "—"), defaulted(e.Default, "—"), oneLine(e.Description)))
	}
	return b.String()
}

func renderPreset(p preset, entities map[string]map[string]entity) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("\n# Preset — %s\n\n", p.Name))
	b.WriteString(fmt.Sprintf("Auto-derived from `defaults/config/%s.yaml`.\n\n", p.Key))

	// Personas
	b.WriteString("<!-- SECTION:personas -->\n")
	b.WriteString("## Personas\n\n")
	if len(p.Personas) == 0 {
		b.WriteString("_All personas under `defaults/personas/` are eligible (no allowlist)._\n\n")
	} else {
		b.WriteString("| Persona | Skills |\n|---|---|\n")
		sort.Slice(p.Personas, func(i, j int) bool { return p.Personas[i].Slug < p.Personas[j].Slug })
		for _, pp := range p.Personas {
			skills := "—"
			if len(pp.Skills) > 0 {
				skills = "`" + strings.Join(pp.Skills, "`, `") + "`"
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s |\n", pp.Slug, skills))
		}
		b.WriteString("\n")
	}
	b.WriteString("<!-- END SECTION -->\n\n")

	// MCP bindings
	b.WriteString("<!-- SECTION:mcp-commands -->\n")
	b.WriteString("## MCP command bindings\n\n")
	if len(p.MCPCommands) == 0 {
		b.WriteString("_No MCP command overrides._\n\n")
	} else {
		b.WriteString("| Command | Persona | Laws (+/-) | Templates |\n|---|---|---|---|\n")
		cmds := make([]string, 0, len(p.MCPCommands))
		for k := range p.MCPCommands {
			cmds = append(cmds, k)
		}
		sort.Strings(cmds)
		for _, c := range cmds {
			binding := p.MCPCommands[c]
			lawCol := formatLaws(binding.Laws, binding.LawsDisabled)
			tplCol := "—"
			if len(binding.Templates) > 0 {
				tplCol = "`" + strings.Join(binding.Templates, "`, `") + "`"
			}
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n", c, defaulted(binding.Persona, "—"), lawCol, tplCol))
		}
		b.WriteString("\n")
	}
	b.WriteString("<!-- END SECTION -->\n\n")

	// Workflow guards
	b.WriteString("<!-- SECTION:workflow-guards -->\n")
	b.WriteString("## Workflow guards\n\n")
	for _, w := range p.Workflows {
		b.WriteString(fmt.Sprintf("### `%s` workflow\n\n", w.Key))
		bucketLabel := map[int]string{}
		for _, bk := range w.Buckets {
			bucketLabel[bk.ID] = bk.Key
		}
		if len(w.Operations) > 0 {
			b.WriteString("**Operations**\n\n")
			b.WriteString("| Operation | Guards |\n|---|---|\n")
			ops := make([]string, 0, len(w.Operations))
			for op := range w.Operations {
				ops = append(ops, op)
			}
			sort.Strings(ops)
			for _, op := range ops {
				b.WriteString(fmt.Sprintf("| `%s` | %s |\n", op, formatGuards(w.Operations[op].Guards)))
			}
			b.WriteString("\n")
		}
		if len(w.Transitions) > 0 {
			b.WriteString("**Transitions**\n\n")
			b.WriteString("| From | To | Guards |\n|---|---|---|\n")
			for _, t := range w.Transitions {
				from := defaulted(bucketLabel[t.From], fmt.Sprintf("#%d", t.From))
				to := defaulted(bucketLabel[t.To], fmt.Sprintf("#%d", t.To))
				b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", from, to, formatGuards(t.Guards)))
			}
			b.WriteString("\n")
		}
	}
	b.WriteString("<!-- END SECTION -->\n")

	return b.String()
}

func renderTagVocabulary(presets []preset) string {
	type usage struct {
		Tag     string
		Presets map[string]map[string]struct{} // preset → context (e.g. "transition backlog→dev")
	}
	tags := map[string]*usage{}
	add := func(tag, presetKey, ctx string) {
		if tag == "" {
			return
		}
		u, ok := tags[tag]
		if !ok {
			u = &usage{Tag: tag, Presets: map[string]map[string]struct{}{}}
			tags[tag] = u
		}
		if _, ok := u.Presets[presetKey]; !ok {
			u.Presets[presetKey] = map[string]struct{}{}
		}
		u.Presets[presetKey][ctx] = struct{}{}
	}
	for _, p := range presets {
		for _, w := range p.Workflows {
			bucketLabel := map[int]string{}
			for _, bk := range w.Buckets {
				bucketLabel[bk.ID] = bk.Key
			}
			for op, ops := range w.Operations {
				for _, g := range ops.Guards {
					if g.Type == "comments_tagged" {
						add(g.Tag, p.Key, fmt.Sprintf("op `%s`", op))
					}
				}
			}
			for _, t := range w.Transitions {
				for _, g := range t.Guards {
					if g.Type == "comments_tagged" {
						ctx := fmt.Sprintf("`%s`→`%s`", defaulted(bucketLabel[t.From], fmt.Sprintf("#%d", t.From)), defaulted(bucketLabel[t.To], fmt.Sprintf("#%d", t.To)))
						add(g.Tag, p.Key, ctx)
					}
				}
			}
		}
	}

	keys := make([]string, 0, len(tags))
	for k := range tags {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n# Tag Vocabulary\n\n")
	b.WriteString("Tags that gate workflow operations across the official presets. Add a comment with the matching tag (see `comments.add` `tags:`).\n\n")
	b.WriteString("| Tag | Used in |\n|---|---|\n")
	for _, k := range keys {
		u := tags[k]
		uses := []string{}
		presetKeys := make([]string, 0, len(u.Presets))
		for pk := range u.Presets {
			presetKeys = append(presetKeys, pk)
		}
		sort.Strings(presetKeys)
		for _, pk := range presetKeys {
			ctxs := make([]string, 0, len(u.Presets[pk]))
			for ctx := range u.Presets[pk] {
				ctxs = append(ctxs, ctx)
			}
			sort.Strings(ctxs)
			uses = append(uses, fmt.Sprintf("**%s**: %s", pk, strings.Join(ctxs, ", ")))
		}
		b.WriteString(fmt.Sprintf("| `#%s` | %s |\n", k, strings.Join(uses, " · ")))
	}
	return b.String()
}

// ---- marker engine ----

var (
	autoCatalogRe = regexp.MustCompile(`(?s)<!-- BEGIN auto:catalog kind=([a-z]+) -->\n.*?<!-- END auto:catalog -->`)
	includeRe     = regexp.MustCompile(`(?s)<!-- BEGIN include:([^\s>]+) -->\n.*?<!-- END include -->`)
	sectionReFmt  = `(?s)<!-- SECTION:%s -->\n(.*?)<!-- END SECTION -->`
)

func processMarkers(docsDir string, generated map[string]string, check bool, diffs *[]string) error {
	return filepath.WalkDir(docsDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".md") {
			return nil
		}
		if strings.Contains(path, string(os.PathSeparator)+"_generated"+string(os.PathSeparator)) {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fences := codeFenceSpans(raw)
		updated := raw

		updated = replaceOutsideFences(updated, autoCatalogRe, func(match []byte) []byte {
			sub := autoCatalogRe.FindSubmatch(match)
			kind := string(sub[1])
			rel := fmt.Sprintf(".docs/_generated/entities-%s.md", kind)
			body, ok := generated[rel]
			if !ok {
				return match
			}
			body = stripGeneratedHeader(body)
			return []byte(fmt.Sprintf("<!-- BEGIN auto:catalog kind=%s -->\n%s<!-- END auto:catalog -->", kind, body))
		}, fences)

		// Recompute fences after the first pass; auto-catalog replacements
		// can shift later byte offsets enough that the second pass would
		// reuse stale spans.
		fences = codeFenceSpans(updated)
		updated = replaceOutsideFences(updated, includeRe, func(match []byte) []byte {
			sub := includeRe.FindSubmatch(match)
			target := string(sub[1])
			rel, section := splitTarget(target)
			fullRel := filepath.Join(".docs", rel)
			content, ok := generated[fullRel]
			if !ok {
				diskPath := filepath.Join(filepath.Dir(docsDir), fullRel)
				raw2, err := os.ReadFile(diskPath)
				if err != nil {
					return match
				}
				content = string(raw2)
			}
			content = stripGeneratedHeader(content)
			body := content
			if section != "" {
				re := regexp.MustCompile(fmt.Sprintf(sectionReFmt, regexp.QuoteMeta(section)))
				m := re.FindStringSubmatch(content)
				if len(m) >= 2 {
					body = m[1]
				} else {
					return match
				}
			}
			body = strings.TrimRight(body, "\n") + "\n"
			return []byte(fmt.Sprintf("<!-- BEGIN include:%s -->\n%s<!-- END include -->", target, body))
		}, fences)

		if bytes.Equal(raw, updated) {
			return nil
		}
		if check {
			rel, _ := filepath.Rel(filepath.Dir(docsDir), path)
			*diffs = append(*diffs, rel)
			return nil
		}
		return os.WriteFile(path, updated, 0o644)
	})
}

type span struct{ start, end int }

// codeFenceSpans returns byte ranges (start inclusive, end exclusive) covered
// by triple-backtick fenced code blocks. Used to suppress marker replacement
// inside example snippets in AUTHORING.md and similar docs.
func codeFenceSpans(b []byte) []span {
	var out []span
	lines := bytes.Split(b, []byte("\n"))
	offset := 0
	openStart := -1
	for _, line := range lines {
		trimmed := bytes.TrimLeft(line, " \t")
		if bytes.HasPrefix(trimmed, []byte("```")) {
			if openStart < 0 {
				openStart = offset
			} else {
				out = append(out, span{openStart, offset + len(line) + 1})
				openStart = -1
			}
		}
		offset += len(line) + 1
	}
	return out
}

func insideAny(pos int, spans []span) bool {
	for _, s := range spans {
		if pos >= s.start && pos < s.end {
			return true
		}
	}
	return false
}

func replaceOutsideFences(src []byte, re *regexp.Regexp, repl func([]byte) []byte, fences []span) []byte {
	matches := re.FindAllIndex(src, -1)
	if len(matches) == 0 {
		return src
	}
	var b bytes.Buffer
	last := 0
	for _, m := range matches {
		if insideAny(m[0], fences) {
			continue
		}
		b.Write(src[last:m[0]])
		b.Write(repl(src[m[0]:m[1]]))
		last = m[1]
	}
	b.Write(src[last:])
	return b.Bytes()
}

func splitTarget(s string) (rel, section string) {
	if i := strings.Index(s, "#"); i >= 0 {
		return s[:i], s[i+1:]
	}
	return s, ""
}

// stripGeneratedHeader drops the leading "<!-- GENERATED ... -->" comment line
// (the docs:refresh banner, or the hand-maintained prompt-costs / requirements
// variants) before splicing content into a marker block in another doc — the
// surrounding file already names the source on the BEGIN marker.
func stripGeneratedHeader(s string) string {
	if strings.HasPrefix(s, "<!-- GENERATED") {
		if i := strings.Index(s, "\n"); i >= 0 {
			s = s[i+1:]
		}
	}
	return strings.TrimLeft(s, "\n")
}

// ---- helpers ----

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func sortedKeys(m map[string]entity) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func defaulted(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.TrimSpace(s)
}

func firstParagraph(body string) string {
	s := strings.TrimSpace(body)
	if s == "" {
		return ""
	}
	if i := strings.Index(s, "\n\n"); i >= 0 {
		s = s[:i]
	}
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

func titleize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func formatLaws(add, disabled []string) string {
	parts := []string{}
	if len(add) > 0 {
		parts = append(parts, "+`"+strings.Join(add, "`, +`")+"`")
	}
	if len(disabled) > 0 {
		parts = append(parts, "-`"+strings.Join(disabled, "`, -`")+"`")
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, " · ")
}

func formatGuards(gs []guard) string {
	if len(gs) == 0 {
		return "—"
	}
	parts := make([]string, 0, len(gs))
	for _, g := range gs {
		switch g.Type {
		case "comments_tagged":
			c := g.Count
			if c == 0 {
				c = 1
			}
			parts = append(parts, fmt.Sprintf("`#%s`×%d", g.Tag, c))
		case "blockers_in":
			parts = append(parts, fmt.Sprintf("blockers in `%s`", strings.Join(g.Buckets, "`,`")))
		case "comments_min":
			parts = append(parts, fmt.Sprintf("≥%d comments", g.Count))
		default:
			parts = append(parts, "`"+g.Type+"`")
		}
	}
	return strings.Join(parts, " · ")
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "okt-docs-refresh: "+format+"\n", args...)
	os.Exit(1)
}
